### ISSUE TITLE
Support for Spring Boot 3

### ISSUE THREAD

**Issue by rvullriede** [faucet-pipeline/faucet-pipeline-spring-boot-starter#19]
Spring Boot 3 is currently not supported for two major reasons: 

1. The javax.* namespace is no longer supported and need to be replaced with jakarta.*.
2. The AutoConfiguration mechanism via spring.factories is no longer supported.
3. In addition, certain dependencies are not compatible with Java 17.
4

**Comment by rvullriede** [comment]
You'll find a PR to fix all issues for Spring Boot 3.0.x here: https://github.com/faucet-pipeline/faucet-pipeline-spring-boot-starter/pull/18

I've tested it successfully with my own Spring Boot 3 app and both demo apps are also working as expected.

**Comment by michael-simons** [comment]
Closed with #18 in c01d01ace659c29e1e7f425d021ba034d8158522. Thank you!
